<?php

namespace MaxDillaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduktRepository extends EntityRepository
{
}
