<?php

namespace MaxDillaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZamowienieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZamowienieRepository extends EntityRepository
{
}
